### ISSUE TITLE
Can You Update to RC6 ?

### ISSUE THREAD

**Issue by Nebula-Spark** [bertofer/angular2-electron#2]
It Would Be great If You can Update To RC6  !

**Comment by bortexz** [comment]
Tried to just change package.json and run, and got a ton of errors. I will have a look later to fix everything

**Comment by Nebula-Spark** [comment]
Thank you , Waiting  For  The Update :)

**Comment by bortexz** [comment]
I have upgraded to angular2 RC6 and switched the router-deprecated by the new one

**Comment by Nebula-Spark** [comment]
Thank You :+1:
