### ISSUE TITLE
Live Reload Is Not working

### ISSUE THREAD

**Issue by Nebula-Spark** [bertofer/angular2-electron#3]
Using  npm  run start-watch      , live reloading  is not working ,

and i am getting a following error

Not allowed to load local resource: file:///C:/Offline-Apps/ElectronRc6/dist/     data:text/html,chro…:1

**Comment by bortexz** [comment]
I have investigated a little bit about that, and collected some open issues about it. I also opened one myself in electron-connect. But none of them seem to give a proper solution/fix yet. Will keep updated:
- https://github.com/electron/electron/issues/5107
- https://github.com/electron/electron/issues/4867
- https://github.com/yan-foto/electron-reload/issues/11
- https://github.com/Quramy/electron-connect/issues/60

**Comment by Nebula-Spark** [comment]
@bertofer  I found a solution for live reload ,

just removed the  <base href="./"> 
from public/index.html

And added  
export const routing = RouterModule.forRoot(routes, { useHash: true });
in  app.routing.ts 

And it's works !...

**Comment by bortexz** [comment]
Hi @Nishanth2 , fixed, thanks for the help!

**Comment by eminoda** [comment]
i got 2 way to fix it.
1. set base href ='' on the 'index.html'
2. or, set webcontent event listent in electron main.js(reload URL)
still use angular2 hashpush feature
````
<base href="">
or
// Open the DevTools.
  // 调试
  win.webContents.openDevTools();
  win.webContents.on('devtools-reload-page', () => {
    console.log('devtools-reload-page');
    win.loadURL(url.format({
      pathname: path.join(__dirname, './dist/index.html'),
      protocol: 'file:',
      slashes: true
    }))
  })
````
