### ISSUE TITLE
Request For Angular2 Final 2.0 With Pouch DB Node Adapter And Jquery 

### ISSUE THREAD

**Issue by Nebula-Spark** [bertofer/angular2-electron#4]
Hi ,
It Would Be Great If You Can Update The Repo With  Latest 2.0 and Pouchdb Node Adapter For offline Database Service  including The Webpack.config File ,

I tried Updating to Angular 2.0 and It successfully Done But  Once I add 
npm install pouchdb-node  

The Problem starts ! the  Pouchdb Node Adapter and  JQuery! ,

I Know I am asking A Lot < But It would be A Great startup for me , IF You can Update the repo , Because I an  just A newbie and started coding   a month before Only !

**Comment by bortexz** [comment]
Hi @Nishanth2 , I will update to angular2 final when I have some free time ;) 

For the PouchDB-node-adapter and JQuery, I prefer to keep this repo as simple as possible, with just angular2.

**Comment by bortexz** [comment]
Completed in https://github.com/bertofer/angular2-electron/commit/545713dc52beeceb32c166e0dc4837f07eb28ed2
